jobs:
  include:
#    - stage: test
#      language: node_js
#      node_js: node
#      cache:
#        directories: [node_modules]

#    - stage: build
#      language: android
#      jdk: oraclejdk8
#      android:
#        components:
#          - build-tools-23.0.1
#          - android-23
#          - extra-android-m2repository
#          - extra-android-support
#      cache:
#        directories:
#          - ~/.gradle/caches
#          - ~/.gradle/wrappers
#      script:
#        - nvm install node
#        - npm i -g react-native-cli
#        - react-native init App
#        - cd App
#        - npm i
#        - npm i react-native-amap3d
#        - react-native link
#        - cd android
#        - ./gradlew build
#        - ls -l app/build/outputs/apk

    - stage: build
      language: objective-c
      osx_image: xcode9.1
      cache:
        directories:
          - ~/.rncache
          - ~/Library/Caches/CocoaPods/Pods
      script:
        - nvm install node
        - npm i -g react-native-cli
        - react-native init App
        - cd App
        - npm i
        - npm i react-native-amap3d
        - cd ios
        - echo -e "platform :ios, '8.0'\n\ntarget 'App' do\n  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'\n  pod 'React', path: '../node_modules/react-native/'\n  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/'\nend" > Podfile
        - pod install
        - xcodebuild -workspace RNAMap3D.xcworkspace -scheme RNAMap3D -sdk iphonesimulator -quiet
