version: 2

aliases:
  - &restore-cache-example
    key: example-{{ checksum "example/package-lock.json" }}

  - &save-cache-example
    paths: [example/node_modules]
    key: example-{{ checksum "example/package-lock.json" }}

  - &install-nodejs
    name: Install NodeJS
    command: |
      curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      sudo apt install -y nodejs

  - &install-example-dependencies
    working_directory: example
    command: npm i

  - &restore-cache-android
    key: android

  - &save-cache-android
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
      - /opt/android/sdk
    key: android

jobs:
  test-js:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: package-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          paths: [node_modules]
          key: package-{{ checksum "package-lock.json" }}
      - run: npm test

  test-android-example:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      - TERM: dumb
    steps:
      - checkout
      - run: *install-nodejs
      - restore_cache: *restore-cache-example
      - run: *install-example-dependencies
      - save_cache: *save-cache-example
      - restore_cache: *restore-cache-android
      - run:
          name: Build
          working_directory: example/android
          command: |
            ./gradlew assembleDebug
            ./gradlew assembleRelease
            ls -l app/build/outputs/apk
      - save_cache: *save-cache-android

workflows:
  version: 2
  test:
    jobs:
      - test-js
      - test-android-example
